apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: db
    spec:
      containers:
        - args:
            - mysqld
            - --default-authentication-plugin=mysql_native_password
          env:
            - name: MARIADB_DATABASE
              value: rest_with_spring
            - name: MARIADB_PASSWORD
              value: admin123
            - name: MARIADB_ROOT_HOST
              value: '%'
            - name: MARIADB_ROOT_PASSWORD
              value: admin123
            - name: MARIADB_USER
              value: docker
            - name: MYSQL_TCP_PORT
              value: "3308"
            - name: TZ
              value: America/Sao_Paulo
          image: mariadb:10.10
          name: db
          ports:
            - containerPort: 3308
          resources: {}
      restartPolicy: Always
status: {}
