version: '3.9'

services: 
  db:
    image: mariadb:10.10
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      TZ: America/Sao_Paulo
      MARIADB_ROOT_PASSWORD: admin123
      MARIADB_USER: docker
      MARIADB_PASSWORD: admin123
      MARIADB_DATABASE: rest_with_spring
      MARIADB_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308

  simple-rest-api:
    image: danielnakajima/simple-rest-api
    restart: always
    build: ./
    working_dir: /usr/src/mymaven
    environment: 
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mariadb://db:3308/simplerestapi?createDatabaseIfNotExist=true&&user=root&password=admin123
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123
    command: mvn spring-boot:run
    volumes:
      - .:/usr/src/mymaven:rw
    ports: 
      - 8080:8080
      - 35729:35729
      - 5005:5005
    depends_on: 
      - db
